In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([2,5,10])
a.dtype  # datatype


dtype('int32')

In [4]:
b = np.array([2.3,6.0])
b.dtype

dtype('float64')

In [5]:
# a,b are 1D array

In [6]:
c = np.array([[1,2 ,3],[4,5,6]])  # 2D array [ [raw1] , [raw2] ]
c.dtype

dtype('int32')

In [7]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
d = np.array([3 , 6 , 8 ],dtype="complex") # datatype = complex number ( J:Imaginary part )

In [9]:
d  # complex numbers

array([3.+0.j, 6.+0.j, 8.+0.j])

In [10]:
z = np.zeros((4,3))  # 4:number_of_row , 3:number_of_columns 

In [11]:
z.dtype

dtype('float64')

In [12]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
z.shape # display matrix dimension

(4, 3)

In [14]:
on = np.ones((3,3))

In [15]:
on

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
    # 3D > 2 sett of 3*4 matrix | | default it comes 'float64' dtype 
onw = np.ones((2,3,4),dtype="int32") 

In [17]:
onw

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [18]:
onw.dtype

dtype('int32')

In [19]:
     # like range function used in for loop
a = np.arange(5,27,5) 

In [20]:
a

array([ 5, 10, 15, 20, 25])

In [21]:
      # create a array 2 to 11 with 7 uniform intervals
b = np.linspace(2,11,7)

In [22]:
b

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. ])

In [23]:
c = np.arange(0,100,5)

In [24]:
c

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [25]:
c.shape # not its 1D array 

(20,)

In [26]:
# we can reshape it into 2D 
c.reshape((5,4))

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [27]:
# we can reshape it into 3D
c.reshape((2,2,5))

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

In [28]:
a = np.array([3,4,7,8,9])
b = np.array([1,4,6,10,5])

In [29]:
diff = a - b  # matrix substraction

In [30]:
diff

array([ 2,  0,  1, -2,  4])

In [31]:
add = a + b  # matrix addition

In [32]:
add

array([ 4,  8, 13, 18, 14])

In [33]:
powe =  b**2  # power by 2

In [34]:
powe

array([  1,  16,  36, 100,  25])

In [35]:
x = 0,90,180,360
y = np.sin(x)  # sin() values

In [36]:
y

array([ 0.        ,  0.89399666, -0.80115264,  0.95891572])

In [37]:
   # logic operations on array b
b<9  

array([ True,  True,  True, False,  True])

In [38]:
a = np.array([[2,3],[1,1]])
b = np.array([[1,2],[3,4]])

In [39]:
a+b

array([[3, 5],
       [4, 5]])

In [40]:
    # normal multiplication ( not matrix multiplication )
a*b

array([[2, 6],
       [3, 4]])

In [41]:
a@b # matrix multiplication

array([[11, 16],
       [ 4,  6]])

In [42]:
a.dot(b) # same as matrix multiplication

array([[11, 16],
       [ 4,  6]])

In [43]:
# to create random elements in a matrix
np.random.random((3,4))

array([[0.90769548, 0.07090833, 0.17030721, 0.75601109],
       [0.3548135 , 0.50571781, 0.85670848, 0.44786168],
       [0.62216419, 0.21900926, 0.1007946 , 0.09192598]])

In [44]:
d = np.array([16,13,9,25,15])

In [45]:
d.sum() # sum of all elements in a matrix

78

In [46]:
d.min() # minimum value  : element in a matrix

9

In [47]:
d.max() # maximum value  : element in a matrix

25

In [48]:
b = np.arange(12).reshape(3,4)

In [49]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
b.sum(axis=0) 
#  axis=0 :: column wise
#     0+4+8 = 12
#     1+5+9 = 15
#       etc....


array([12, 15, 18, 21])

In [51]:
b.min(axis=1)
# axis = 1 :: raw wise

array([0, 4, 8])

In [52]:
b.cumsum(axis=1)
# cumulative sum

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [53]:
b = np.array([0,2,4])

In [54]:
np.exp(b) # exponential values

array([ 1.        ,  7.3890561 , 54.59815003])

In [55]:
np.sqrt(b)

array([0.        , 1.41421356, 2.        ])

In [56]:
d.sort()  # sorting

In [57]:
d

array([ 9, 13, 15, 16, 25])

In [58]:
m = d.copy()

In [59]:
m[2:4]

array([15, 16])

In [82]:
b

array([1, 5])

In [84]:
b.ravel() # any diemention change into 1D

array([1, 5])

In [85]:
b.T  # Transpose of matrix

array([1, 5])

In [86]:
a = np.full((3,3),6)

In [87]:
a

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [88]:
b = np.array([[3,6],[2,12]])

In [89]:
b

array([[ 3,  6],
       [ 2, 12]])

In [90]:
np.linalg.det(b)

23.999999999999993

In [91]:
# define the coefficient matrix A
A = np.array([[2, 4], [6, 8]])
# define the constant vector b
b = np.array([5, 6])
# solve the system of linear equations Ax = b
x = np.linalg.solve(A, b)
print(x)

[-2.    2.25]


In [92]:
# find inverse
ar = np.array([[2, 4],[6, 8]])
ra = np.linalg.inv(ar)
print(ra)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [93]:
print(ar@ra)  # AA^-1 = I

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [94]:
# Trace 
a = np.array([[6, 3, 5], [9, 2, 1], [7, 8, 4]])
rt = np.trace(a)
print(rt)

12


In [95]:
a

array([[6, 3, 5],
       [9, 2, 1],
       [7, 8, 4]])

In [96]:
a = np.array([3,4])
b = np.array([1,5])

In [97]:
np.dot(a,b) # Dot product

23

In [98]:
#                Source i used 
# https://www.youtube.com/watch?v=jUyJujpizh0
# https://www.programiz.com/python-programming/numpy/linear-algebra 
# https://numpy.org/doc/stable/reference/generated/numpy.matrix.H.html
# https://numpy.org/doc/stable/reference/routines.linalg.htm